name: AuthorizedOP
api: ["2.0.0"]
main: com.github.anders233.AuthorizedOP
version: "1.0.1"
author: "Anders,Reiyans"
load: POSTWORLD
commands:
  aop:
    description: OP授权管理
    usage: /aop help
    permission: AuthorizedOP.command.aop
permissions:
  AuthorizedOP.Command.aop:
    description: OP授权管理
    default: true


